# Generated by Django 4.1 on 2022-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Teacher_Photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image/'),
        ),
    ]
