# Generated by Django 4.1 on 2022-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_alter_teachermodel_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Teacher_Photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/'),
        ),
    ]
